image: mcr.microsoft.com/dotnet/sdk:8.0
stages:
  - build
  - docker

build:
  stage: build
  script:
    - make build
  artifacts:
    expire_in: 1hr
    paths:
      - /

build-docker:
    image: docker:latest
    variables:
      DOCKER_DRIVER: overlay
      CRYPTOGRAPHY_DONT_BUILD_RUST: 1
    services:
    - docker:dind
    stage: docker
    environment: staging
    script:
      - echo "Build docker 🐳"
      - docker build . -t=az204-blob-manager-console-${CI_PIPELINE_IID}
    artifacts:
      expire_in: 1hr
      paths:
        - build